# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv("../Instructions/output_data/cities.csv")
weather_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Carnarvon,100,AU,1659270962,48,-24.8667,113.6333,70.39,8.32
1,Rikitea,100,PF,1659270963,74,-23.1203,-134.9692,72.37,19.19
2,Upernavik,70,GL,1659270964,69,72.7868,-56.1549,47.97,9.06
3,Hilo,100,US,1659270916,83,19.7297,-155.0900,73.27,4.61
4,Busselton,100,AU,1659270965,74,-33.6500,115.3333,57.49,14.88
...,...,...,...,...,...,...,...,...,...
578,Majene,100,ID,1659271223,88,-3.5403,118.9707,77.76,6.15
579,Kunmadaras,100,HU,1659271223,54,47.4333,20.8000,72.86,13.87
580,Karratha,23,AU,1659271224,59,-20.7377,116.8463,72.05,5.84
581,Port Shepstone,99,ZA,1659271224,57,-30.7414,30.4550,62.92,21.59
582,Walvis Bay,100,NaN,1659271225,72,-22.9575,14.5053,58.15,9.22

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Store latitude and longitude in locations
locations = weather_data[["Lat", "Lng"]]

# Store Humidity in humidity
humidity = weather_data["Humidity"]

In [4]:
# Plot Heatmap
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)
max_intensity = np.max(humidity)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=100, point_radius=3)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

# Save the figure
plt.savefig("../Instructions/plot_heat_map.png")

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# Narrow down the cities with wind speed less than 10 mph, cloudiness equals to 0 and max temp between 60 and 80
narrowed_city_df = weather_data.loc[(weather_data["Wind Speed"] <= 10) & (weather_data["Cloudiness"] == 0) & \
                                   (weather_data["Max Temp"] >= 70) & (weather_data["Max Temp"] <= 80)].dropna()

narrowed_city_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
17,Rio Verde de Mato Grosso,0,BR,1659270971,38,-18.9181,-54.8442,79.05,6.49
20,Albany,0,US,1659270703,74,42.6001,-73.9662,70.57,1.77
24,Saint George,0,US,1659270973,74,37.1041,-113.5841,75.63,1.99
43,Lata,0,PT,1659270982,17,40.1629,-8.3327,77.81,7.02
99,Tatarskaya Pishlya,0,RU,1659271007,45,54.0608,44.8998,73.92,7.54
101,Bethel,0,US,1659271008,73,41.3712,-73.4140,74.52,0.00
144,Grafton,0,US,1659271029,66,42.2070,-71.6856,77.20,3.44
155,Ponta do Sol,0,PT,1659271033,70,32.6667,-17.1000,79.72,2.84
160,Brownsville,0,US,1659270766,92,25.9018,-97.4975,78.75,4.61
167,Matamoros,0,MX,1659271038,38,25.5333,-103.2500,73.51,4.61
234,Mukhen,0,RU,1659271065,95,48.1000,136.1000,70.20,3.96
235,Uvalde,0,US,1659271066,60,29.3669,-99.7670,73.13,5.75
252,Khani,0,GE,1659271073,51,41.9563,42.9566,74.77,5.93
286,Lagoa,0,PT,1659271089,73,39.0500,-27.9833,72.61,7.78
294,SÃ£o Gabriel da Cachoeira,0,BR,1659271092,94,-0.1303,-67.0892,76.80,2.30
301,Satuk,0,TR,1659271096,42,41.2263,32.3836,78.58,7.70
302,Halifax,0,CA,1659270827,81,44.6453,-63.5724,72.68,6.91
303,Davidson,0,US,1659271097,84,36.1501,-86.7833,76.71,8.99
316,ParaÃºna,0,BR,1659271102,32,-16.9478,-50.4486,79.36,6.11
329,Jatibarang,0,ID,1659271108,80,-6.4747,108.3153,77.59,6.02
332,Houma,0,US,1659270936,94,29.5958,-90.7195,79.00,0.00
346,Mujiayingzi,0,CN,1659271117,67,42.1167,118.7833,75.99,6.15
363,Kingman,0,US,1659271125,71,35.1894,-114.0530,78.28,9.22
385,Mastic Beach,0,US,1659271017,69,40.7668,-72.8521,79.05,6.91
399,Vila Velha,0,BR,1659271142,60,-20.3297,-40.2925,73.35,9.22
418,La Rioja,0,ES,1659271095,39,42.2500,-2.5000,76.78,7.67
420,Yarmouth,0,US,1659271151,68,41.7057,-70.2286,78.15,5.75
460,Jardim,0,BR,1659271170,37,-21.4803,-56.1381,74.53,4.97
513,Yuanping,0,CN,1659271194,69,38.7153,112.7575,74.82,1.43
553,Newton,0,US,1659271177,63,42.3370,-71.2092,78.44,9.22
577,Orangeburg,0,US,1659271223,94,33.4918,-80.8557,78.94,4.00

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
# Create a hotel_df
hotel_df = narrowed_city_df.loc[:,["City","Country", "Lat", "Lng"]]

# Add a "Hotel Name" column to the DataFrame.
hotel_df["Hotel Name"] = ""

# Display the result
hotel_df

                         City Country      Lat       Lng Hotel Name
17   Rio Verde de Mato Grosso      BR -18.9181  -54.8442
20                     Albany      US  42.6001  -73.9662
24               Saint George      US  37.1041 -113.5841
43                       Lata      PT  40.1629   -8.3327
99         Tatarskaya Pishlya      RU  54.0608   44.8998
101                    Bethel      US  41.3712  -73.4140
144                   Grafton      US  42.2070  -71.6856
155              Ponta do Sol      PT  32.6667  -17.1000
160               Brownsville      US  25.9018  -97.4975
167                 Matamoros      MX  25.5333 -103.2500
234                    Mukhen      RU  48.1000  136.1000
235                    Uvalde      US  29.3669  -99.7670
252                     Khani      GE  41.9563   42.9566
286                     Lagoa      PT  39.0500  -27.9833
294  SÃ£o Gabriel da Cachoeira      BR  -0.1303  -67.0892
301                     Satuk      TR  41.2263   32.3836
302                   Halifax      CA  44.6453  -63.5724
303                  Davidson      US  36.1501  -86.7833
316                   ParaÃºna      BR -16.9478  -50.4486
329                Jatibarang      ID  -6.4747  108.3153
332                     Houma      US  29.5958  -90.7195
346               Mujiayingzi      CN  42.1167  118.7833
363                   Kingman      US  35.1894 -114.0530
385              Mastic Beach      US  40.7668  -72.8521
399                Vila Velha      BR -20.3297  -40.2925
418                  La Rioja      ES  42.2500   -2.5000
420                  Yarmouth      US  41.7057  -70.2286
460                    Jardim      BR -21.4803  -56.1381
513                  Yuanping      CN  38.7153  112.7575
553                    Newton      US  42.3370  -71.2092
577                Orangeburg      US  33.4918  -80.8557

In [7]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

for index, row in hotel_df.iterrows():
    # get city name, lat, lnt from df
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    
    # add keyword to params dict
    params["location"] = f"{lat},{lng}"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    # save the hotel name to dataframe
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']

    # if there is no hotel available, show missing field
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")
    
    # Wait 1 sec to make another api request to avoid SSL Error
time.sleep(1)

# Print end of search once searching is completed
print("-------End of Search-------")

Retrieving Results for Index 17: Rio Verde de Mato Grosso.
Closest hotel in Rio Verde de Mato Grosso is Hotel Serra Verde.
------------
Retrieving Results for Index 20: Albany.
Missing field/result... skipping.
------------
Retrieving Results for Index 24: Saint George.
Closest hotel in Saint George is Red Lion Hotel & Conference Center St. George.
------------
Retrieving Results for Index 43: Lata.
Missing field/result... skipping.
------------
Retrieving Results for Index 99: Tatarskaya Pishlya.
Closest hotel in Tatarskaya Pishlya is Khostel Dyushes.
------------
Retrieving Results for Index 101: Bethel.
Closest hotel in Bethel is Hampton Inn Danbury.
------------
Retrieving Results for Index 144: Grafton.
Closest hotel in Grafton is Hunter's Grille & Tap at the Grafton Inn.
------------
Retrieving Results for Index 155: Ponta do Sol.
Closest hotel in Ponta do Sol is Enotel Sunset Bay.
------------
Retrieving Results for Index 160: Brownsville.
Closest hotel in Brownsville is Boca Chica Inn & Suites.
------------
Retrieving Results for Index 167: Matamoros.
Closest hotel in Matamoros is HOTEL PLAZA MATAMOROS.
------------
Retrieving Results for Index 234: Mukhen.
Missing field/result... skipping.
------------
Retrieving Results for Index 235: Uvalde.
Missing field/result... skipping.
------------
Retrieving Results for Index 252: Khani.
Closest hotel in Khani is hotel alismereti.
------------
Retrieving Results for Index 286: Lagoa.
Closest hotel in Lagoa is Graciosa Resort - Biosphere Island Hotel.
------------
Retrieving Results for Index 294: SÃ£o Gabriel da Cachoeira.
Closest hotel in SÃ£o Gabriel da Cachoeira is Pousada Bawary.
------------
Retrieving Results for Index 301: Satuk.
Missing field/result... skipping.
------------
Retrieving Results for Index 302: Halifax.
Closest hotel in Halifax is Halifax Marriott Harbourfront Hotel.
------------
Retrieving Results for Index 303: Davidson.
Closest hotel in Davidson is Millennium Maxwell House Hotel Nashville.
------------
Retrieving Results for Index 316: ParaÃºna.
Closest hotel in ParaÃºna is Hotel Serras de ParaÃºna.
------------
Retrieving Results for Index 329: Jatibarang.
Closest hotel in Jatibarang is Adi Sederhana Hotel.
------------
Retrieving Results for Index 332: Houma.
Closest hotel in Houma is Courtyard by Marriott Houma.
------------
Retrieving Results for Index 346: Mujiayingzi.
Missing field/result... skipping.
------------
Retrieving Results for Index 363: Kingman.
Closest hotel in Kingman is Home2 Suites by Hilton Kingman.
------------
Retrieving Results for Index 385: Mastic Beach.
Closest hotel in Mastic Beach is Smith Point Motel.
------------
Retrieving Results for Index 399: Vila Velha.
Closest hotel in Vila Velha is Quality Suites Vila Velha.
------------
Retrieving Results for Index 418: La Rioja.
Closest hotel in La Rioja is LavidaesSueÃ±o.
------------
Retrieving Results for Index 420: Yarmouth.
Closest hotel in Yarmouth is Isaiah Hall Bed & Breakfast.
------------
Retrieving Results for Index 460: Jardim.
Closest hotel in Jardim is Estancia Hotel - Jardim MS.
------------
Retrieving Results for Index 513: Yuanping.
Closest hotel in Yuanping is é“¶æµ·å®¾é¦†.
------------
Retrieving Results for Index 553: Newton.
Closest hotel in Newton is Sheraton Boston Needham Hotel.
------------
Retrieving Results for Index 577: Orangeburg.
Closest hotel in Orangeburg is Super 8 by Wyndham Orangeburg North.
------------

NameError: name 'time' is not defined

In [ ]:
hotel_df

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [14]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))